# -*-coding:utf-8 -*-
from sqlalchemy import Table, Column, INTEGER, String, Text, Float
from footcom_route.db.basic_db import metadata

# login table
login_info = Table("account", metadata,
                   Column("id", INTEGER, primary_key=True, autoincrement=True),
                   Column("user", String(100), unique=True),
                   Column("password", String(200)),
                   Column("enable", INTEGER, default=0, server_default='0'),
                   Column("headers", Text),
                   )

# route info
route_info = Table("route_info", metadata,
                   Column("order_id", INTEGER, primary_key=True, autoincrement=True),
                   Column("id", INTEGER, unique=True),
                   Column("activity", String(200)),
                   Column("difficulty", String(200)),
                   Column("creator_id", INTEGER),
                   Column("edit_timestamp", String(200)),
                   Column("occurtime", String(200)),
                   Column("create_time", String(200)),
                   Column("timezone", String(200)),
                   Column("duration", INTEGER),
                   Column("start_place_name", Text),
                   Column("end_place_name", Text),
                   Column("distance", Float),
                   Column("speed_max", Float),
                   Column("accum_uphill", INTEGER),
                   Column("accum_downhill", INTEGER),
                   Column("elevation_max", INTEGER),
                   Column("elevation_min", INTEGER),
                   Column("downloads", INTEGER),
                   Column("favorites", INTEGER),
                   Column("comment_times", INTEGER),
                   Column("view_times", INTEGER),
                   Column("name", Text),
                   Column("story", Text),
                   Column("has_footprint", INTEGER),
                   Column("own", INTEGER),
                   Column("is_collected", INTEGER),
                   Column("rating", INTEGER),
                   Column("pic_footprint_count", INTEGER),
                   Column("txt_footprint_count", INTEGER),
                   Column("simply_point_count", INTEGER),
                   Column("creator", String(200)),
                   Column("pic", String(200)),
                   Column("map_type", String(200)),
                   Column("simplyfile_download_path", Text),
                   Column("footprint", Text),
                   Column("creator_avatar", Text),
                   Column("sketch_url", Text),
                   Column("trip", Text),
                   Column("info_last_update", String(200)),
                   Column("track_last_update", String(200)),
                   Column("mark_addible", INTEGER),
                   )
__all__ = ['login_info', 'route_info']
