# coding:utf-8
# the expire time(hours) of each cookies
cookie_expire_time: 23

db:
    host: http://118.24.92.182
    port: 3306
    user: Rain
    password: XxmJArMPAtnBnmsy
    db_name: foot_route
    db_type: mysql
